<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="amr1">
  <xacro:include filename="$(find robots_description)/urdf/amr_base_common.xacro"/>

  <!-- customize AMR-1 -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.025"/>
  <xacro:property name="wheel_base"   value="0.4"/>
  <xacro:property name="chassis_length" value="0.5"/>
  <xacro:property name="chassis_width"  value="0.3"/>
  <xacro:property name="chassis_height" value="0.10"/>
  <xacro:property name="mass_chassis" value="100.0"/>

  <!-- base_link (chassis) -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <xacro:inertial_box m="${mass_chassis}" lx="${chassis_length}" ly="${chassis_width}" lz="${chassis_height}"/>
  </link>

  <!-- left & right wheels -->
  <xacro:wheel name="wheel_left"  radius="${wheel_radius}" width="${wheel_width}" mass="1.0"/>
  <xacro:wheel name="wheel_right" radius="${wheel_radius}" width="${wheel_width}" mass="1.0"/>

  <!-- joints for wheels (continuous for simulation) -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left"/>
    <origin xyz="0 ${wheel_base/2} ${chassis_height/4}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="0 ${-wheel_base/2} ${chassis_height/4}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- caster -->
  <xacro:caster name="caster_link" radius="${caster_radius}" mass="0.3"/>
  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="${-chassis_length/2} 0 ${0.02}" rpy="0 0 0"/>
  </joint>

  <!-- IMU link -->
  <link name="imu_link">
    <origin xyz="0 0 ${chassis_height + 0.02}" rpy="0 0 0"/>
    <visual><geometry><sphere radius="0.02"/></geometry></visual>
    <xacro:inertial_box m="0.05" lx="0.04" ly="0.02" lz="0.02"/>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${chassis_height + 0.02}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR link (2D) -->
  <link name="lidar_link">
    <visual><geometry><cylinder radius="0.03" length="0.02"/></geometry></visual>
    <xacro:inertial_box m="0.05" lx="0.06" ly="0.06" lz="0.02"/>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2 + 0.05}" rpy="0 0 0"/>
  </joint>

  <!-- payload mount -->
  <link name="payload_mount">
    <visual><geometry><box size="0.20 0.20 0.02"/></geometry></visual>
    <xacro:inertial_box m="0.2" lx="0.2" ly="0.2" lz="0.02"/>
  </link>
  <joint name="payload_mount_joint" type="fixed">
    <parent link="base_link"/>
    <child link="payload_mount"/>
    <origin xyz="0 ${chassis_width/2 - 0.1} ${chassis_height/2 + 0.01}" rpy="0 0 0"/>
  </joint>

  <!-- joint_state and robot_state_publisher friendly root -->
  <gazebo reference="base_link"/>
</robot>
