<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="amr2">
  <xacro:include filename="$(find robots_description)/urdf/amr_base_common.xacro"/>

  <!-- customize AMR-2 -->
  <xacro:property name="wheel_radius" value="0.1"/>
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="wheel_base"   value=".75"/>
  <xacro:property name="chassis_length" value="1.0"/>
  <xacro:property name="chassis_width"  value="0.6"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="mass_chassis" value="200.0"/>

  <!-- base -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <geometry><box size="${chassis_length} ${chassis_width} ${chassis_height}"/></geometry>
    </collision>
    <xacro:inertial_box m="${mass_chassis}" lx="${chassis_length}" ly="${chassis_width}" lz="${chassis_height}"/>
  </link>

  <!-- wheels -->
  <xacro:wheel name="wheel_left"  radius="${wheel_radius}" width="${wheel_width}" mass="1.2"/>
  <xacro:wheel name="wheel_right" radius="${wheel_radius}" width="${wheel_width}" mass="1.2"/>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left"/>
    <origin xyz="0 ${wheel_base/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="0 ${-wheel_base/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- caster -->
  <xacro:caster name="caster_link" radius="${caster_radius}" mass="0.3"/>
  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="${-chassis_length/2} 0 ${0.02}" rpy="0 0 0"/>
  </joint>

  <!-- higher precision IMU -->
  <link name="imu_link">
    <visual><geometry><sphere radius="0.02"/></geometry></visual>
    <xacro:inertial_box m="0.04" lx="0.03" ly="0.03" lz="0.02"/>
  </link>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${chassis_height/2 + 0.04}" rpy="0 0 0"/>
  </joint>

  <!-- mast (for lift) -->
  <link name="mast_link">
    <visual><geometry><box size="0.10 0.10 0.30"/></geometry></visual>
    <xacro:inertial_box m="1.0" lx="0.10" ly="0.10" lz="0.30"/>
  </link>
  <joint name="mast_fixed" type="fixed">
    <parent link="base_link"/>
    <child link="mast_link"/>
    <origin xyz="${chassis_length/4} 0 ${chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- lift (prismatic) -->
  <link name="lift_platform">
    <visual><geometry><box size="0.30 0.30 0.02"/></geometry></visual>
    <xacro:inertial_box m="2.0" lx="0.30" ly="0.30" lz="0.02"/>
  </link>

  <joint name="lift_joint" type="prismatic">
    <parent link="mast_link"/>
    <child link="lift_platform"/>
    <origin xyz="0 0 0.15" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="0.60" effort="100.0" velocity="0.2"/>
  </joint>

  <!-- depth camera link on top of lift -->
  <link name="depth_camera_link">
    <visual><geometry><box size="0.06 0.06 0.04"/></geometry></visual>
    <xacro:inertial_box m="0.2" lx="0.06" ly="0.06" lz="0.04"/>
  </link>

  <joint name="camera_mount_joint" type="fixed">
    <parent link="lift_platform"/>
    <child link="depth_camera_link"/>
    <origin xyz="0 0 0.10" rpy="0 0 0"/>
  </joint>

  <!-- small lidar on chassis front -->
  <link name="lidar_link">
    <visual><geometry><cylinder radius="0.03" length="0.02"/></geometry></visual>
    <xacro:inertial_box m="0.05" lx="0.06" ly="0.06" lz="0.02"/>
  </link>
  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2 + 0.05}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="base_link"/>
</robot>
