<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="amr_common">

  <!-- Basic parameters you can override when including -->
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width"  value="0.04"/>
  <xacro:property name="wheel_base"   value="0.40"/> <!-- distance between wheels -->
  <xacro:property name="chassis_length" value="0.55"/>
  <xacro:property name="chassis_width"  value="0.40"/>
  <xacro:property name="chassis_height" value="0.18"/>
  <xacro:property name="caster_radius" value="0.03"/>
  <xacro:property name="mass_chassis" value="12.0"/>

  <!-- inertial helper -->
  <xacro:macro name="inertial_box" params="m lx ly lz">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <!-- approximate inertia for box -->
      <inertia ixx="${(1.0/12.0)*m*(ly*ly + lz*lz)}"
               ixy="0.0" ixz="0.0"
               iyy="${(1.0/12.0)*m*(lx*lx + lz*lz)}"
               iyz="0.0"
               izz="${(1.0/12.0)*m*(lx*lx + ly*ly)}"/>
    </inertial>
  </xacro:macro>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="name radius width mass">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
      <xacro:inertial_box m="${mass}" lx="${radius*2}" ly="${radius*2}" lz="${width}"/>
    </link>
  </xacro:macro>

  <!-- Simple caster wheel -->
  <xacro:macro name="caster" params="name radius mass">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${radius}" length="${radius*0.5}"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${radius}" length="${radius*0.5}"/>
        </geometry>
      </collision>
      <xacro:inertial_box m="${mass}" lx="${radius*2}" ly="${radius*2}" lz="${radius*0.5}"/>
    </link>
  </xacro:macro>

</robot>
