<?xml version="1.0"?>
<robot name="picker"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:arg name="robot_name" default="picker_X"/>

  <xacro:include filename="$(find robots_description)/urdf/picker.gazebo.xacro"/>

  <xacro:macro name="picker_model" params="robot_name">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.45"/>
    <xacro:property name="base_height" value="0.18"/>
    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_width" value="0.04"/>
    <xacro:property name="wheel_gap_from_base" value="0.01"/>
    <xacro:property name="wheel_separation" value="${base_width/2 + wheel_width/2 + wheel_gap_from_base}"/>

    <link name="${robot_name}/robot">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="25.0"/>
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.2" iyz="0.0" izz="1.2"/>
      </inertial>
      <visual>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <origin xyz="0 0 ${base_height/2}"/>
        <material name="green">
          <color rgba="0.01 1 0 1.0"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <origin xyz="0 0 ${base_height/2}"/>
      </collision>
    </link>

    <joint name="${robot_name}/joint_left_wheel" type="continuous">
      <parent link="${robot_name}/robot"/>
      <child link="${robot_name}/left_wheel"/>
      <origin xyz="0 ${wheel_separation} ${wheel_radius/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${robot_name}/left_wheel">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${robot_name}/joint_right_wheel" type="continuous">
      <parent link="${robot_name}/robot"/>
      <child link="${robot_name}/right_wheel"/>
      <origin xyz="0 -${wheel_separation} ${wheel_radius/2}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>

    <link name="${robot_name}/right_wheel">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.8"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${robot_name}/caster_joint_back" type="fixed">
      <parent link="${robot_name}/robot"/>
      <child link="${robot_name}/caster_link_back"/>
      <origin xyz="-${base_length/4} 0 0"/>
    </joint>

    <link name="${robot_name}/caster_link_back">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <sphere radius="0.04"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.04"/>
        </geometry>
      </collision>
    </link>


    <joint name="${robot_name}/caster_joint_front" type="fixed">
      <parent link="${robot_name}/robot"/>
      <child link="${robot_name}/caster_link_front"/>
      <origin xyz="${base_length/4} 0 0"/>
    </joint>

    <link name="${robot_name}/caster_link_front">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <sphere radius="0.04"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.04"/>
        </geometry>
      </collision>
    </link>

    <joint name="${robot_name}/lidar_joint" type="fixed">
      <parent link="${robot_name}/robot"/>
      <child link="${robot_name}/lidar"/>
      <origin xyz="${base_length/2-0.05} 0 ${base_height+0.03}" rpy="0 0 0"/>
    </joint>

    <link name="${robot_name}/lidar">
      <visual>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.06"/>
        </geometry>
        <material name="purple">
          <color rgba="0.1 0.01 0.8 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0"/>
        <geometry>
          <cylinder radius="0.04" length="0.06"/>
        </geometry>
      </collision>
    </link>

    <joint name="${robot_name}/imu_joint" type="fixed">
      <parent link="${robot_name}/robot"/>
      <child link="${robot_name}/imu"/>
      <origin xyz="0 0 ${base_height/2}"/>
    </joint>

    <link name="${robot_name}/imu"/>


    <xacro:picker_gazebo robot_name="$(arg robot_name)"/>

  </xacro:macro>
</robot>
