<?xml version="1.0"?>

<robot name="tug_gazebo"
	xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:arg name="robot_name" default="tug_X"/>

	<xacro:macro name="tug_gazebo" params="robot_name">

		<xacro:property name="base_length" value="0.6"/>
		<xacro:property name="base_width" value="0.45"/>
		<xacro:property name="base_height" value="0.18"/>
		<xacro:property name="wheel_radius" value="0.08"/>
		<xacro:property name="wheel_width" value="0.04"/>
		<xacro:property name="wheel_gap_from_base" value="0.01"/>
		<xacro:property name="wheel_separation" value="${base_width/2 + wheel_width/2 + wheel_gap_from_base}"/>

		<gazebo reference="${robot_name}/left_wheel">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<kp>1000000.0</kp>
			<kd>100.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>1.0</maxVel>
		</gazebo>

		<gazebo reference="${robot_name}/right_wheel">
			<mu1>1.0</mu1>
			<mu2>1.0</mu2>
			<kp>1000000.0</kp>
			<kd>100.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>1.0</maxVel>
		</gazebo>

		<gazebo reference="${robot_name}/caster_link_back">
			<mu1>0.0</mu1>
			<mu2>0.0</mu2>
			<kp>1000000.0</kp>
			<kd>100.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>1.0</maxVel>
		</gazebo>

		<gazebo reference="${robot_name}/caster_link_front">
			<mu1>0.0</mu1>
			<mu2>0.0</mu2>
			<kp>1000000.0</kp>
			<kd>100.0</kd>
			<minDepth>0.001</minDepth>
			<maxVel>1.0</maxVel>
		</gazebo>

		<gazebo>
			<plugin name='${robot_name}_diff_drive_gazebo_plugin' filename='libgazebo_ros_diff_drive.so'>
				<ros>
					<namespace>${robot_name}</namespace>
				</ros>

				<!-- wheels -->
				<left_joint>${robot_name}/joint_left_wheel</left_joint>
				<right_joint>${robot_name}/joint_right_wheel</right_joint>

				<!-- kinematics -->
				<wheel_separation>${wheel_separation}</wheel_separation>
				<wheel_diameter>${2*wheel_radius}</wheel_diameter>

				<!-- limits -->
				<max_wheel_torque>20</max_wheel_torque>
				<max_wheel_acceleration>1.0</max_wheel_acceleration>

				<!-- output -->
				<publish_odom>true</publish_odom>
				<publish_odom_tf>true</publish_odom_tf>
				<publish_wheel_tf>true</publish_wheel_tf>

				<odometry_frame>world</odometry_frame>
				<robot_base_frame>${robot_name}/base_link</robot_base_frame>
			</plugin>
		</gazebo>

	</xacro:macro>
</robot>