<?xml version="1.0"?>

<robot name="common_gazebo"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="ns" default="picker_X"/>
    <xacro:macro name="common_gazebo" params="ns">

        <gazebo reference="${ns}/left_wheel">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>1.0</maxVel>
            <material>Gazebo/Black</material>
        </gazebo>

        <gazebo reference="${ns}/right_wheel">
            <mu1>1.0</mu1>
            <mu2>1.0</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>1.0</maxVel>
            <material>Gazebo/Black</material>
        </gazebo>

        <gazebo reference="${ns}/caster_link_back">
            <mu1>0.0</mu1>
            <mu2>0.0</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>1.0</maxVel>
            <material>Gazebo/Black</material>
        </gazebo>

        <gazebo reference="${ns}/caster_link_front">
            <mu1>0.0</mu1>
            <mu2>0.0</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>1.0</maxVel>
            <material>Gazebo/Black</material>
        </gazebo>


        <gazebo>
            <plugin name='${ns}_diff_drive_gazebo_plugin' filename='libgazebo_ros_diff_drive.so'>
                <ros>
                    <namespace>${ns}</namespace>
                </ros>

                <!-- wheels -->
                <left_joint>${ns}/joint_left_wheel</left_joint>
                <right_joint>${ns}/joint_right_wheel</right_joint>

                <!-- kinematics -->
                <wheel_separation>${wheel_separation}</wheel_separation>
                <wheel_diameter>${2*wheel_radius}</wheel_diameter>

                <!-- limits -->
                <max_wheel_torque>20</max_wheel_torque>
                <max_wheel_acceleration>1.0</max_wheel_acceleration>

                <!-- output -->
                <publish_odom>true</publish_odom>
                <publish_odom_tf>true</publish_odom_tf>
                <publish_wheel_tf>true</publish_wheel_tf>

                <odometry_frame>${ns}/odom</odometry_frame>
                <robot_base_frame>${ns}/robot</robot_base_frame>
            </plugin>
        </gazebo>


        <gazebo reference="${ns}/lidar">
            <material>Gazebo/Blue</material>
            <sensor name="lidar" type="ray">
                <always_on>true</always_on>
                <update_rate>10</update_rate>                <!-- scan frequency in Hz -->
                <visualize>false</visualize>

                <!-- Laser ray configuration -->
                <ray>
                    <scan>
                        <horizontal>
                            <samples>720</samples>                            <!-- number of points per scan (low precision) -->
                            <resolution>0.05</resolution>
                            <min_angle>-1.57</min_angle>                            <!-- -90 degrees -->
                            <max_angle>1.57</max_angle>                            <!-- 90 degrees -->
                        </horizontal>
                    </scan>
                    <range>
                        <min>0.1</min>
                        <max>5.0</max>
                        <resolution>0.01</resolution>
                    </range>
                    <!-- Low-precision Gaussian noise -->
                    <noise type="gaussian">
                        <mean>0.0</mean>
                        <stddev>0.05</stddev>
                    </noise>
                </ray>

                <plugin name="${ns}_lidar_gazebo_plugin" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <namespace>${ns}</namespace>
                        <remapping>~/out:=lidar/points</remapping>
                    </ros>
                    <output_type>sensor_msgs/LaserScan</output_type>
                    <min_intensity>100.0</min_intensity>
                    <frame_name>${ns}/lidar</frame_name>
                </plugin>

                <pose>0 0 0 0 0 0</pose>                <!-- adjust height above base_link -->
            </sensor>
        </gazebo>

    </xacro:macro>
</robot>